### ISSUE TITLE
Error when shooting Priest to Sidekick

### ISSUE THREAD

**Issue by Blaubeeree** [TTT-2/ttt2-role_pri#4] opened 2019-08-01 11:46 UTC
When the Priest gets Sidekick he doesn't see who is Jackal and the Hud says he isn't in a Team.
![image](https://user-images.githubusercontent.com/47636067/62290645-1c884c80-b462-11e9-8543-21470d559080.png)
![image](https://user-images.githubusercontent.com/47636067/62290566-e6e36380-b461-11e9-88c5-96f4acb52bb3.png)

If the players who were in the brotherhood get killed you cant identify them.
![image](https://user-images.githubusercontent.com/47636067/62290848-8ef92c80-b462-11e9-9bce-dd495b64e365.png)
![image](https://user-images.githubusercontent.com/47636067/62290752-5fe2bb00-b462-11e9-8813-01ae46f40829.png)

**Comment by TimGoll** [comment] 2019-08-01 11:56
Both errors seam to be sidekick related, am I right? I will look into it

**Comment by TimGoll** [comment] 2019-08-01 11:59
The first error is an oversight, should be easy to fix. Maybe the other error is connected to this issue.
But shooting the priest to a sidekick isn't changed at all. Does this problem only occur for the other members of the brotherhood?

**Comment by Blaubeeree** [comment] 2019-08-01 12:03
Yes only for the other members not for the priest

**Comment by TimGoll** [comment] 2019-08-01 12:05
Okay. I think I know the problem. I might fix it today in the evening, should be a quick fix

**Comment by Blaubeeree** [comment] 2019-08-01 12:06
But the problem that the sidekick doent see who is jackal occur for the priest (i dont know if this occur for the members too, we couldnt test this)

**Comment by TimGoll** [comment] 2019-08-01 12:12
This might be caused by the netmessage error which might be caused by the Brotherhood members. 
Otherwise I see no reason for it to fail because I haven't changed anything in the jackal/sidekick code

**Comment by TimGoll** [comment] 2019-08-02 08:15
I kinda fixed it yesterday. There's still a sidekick color sync error. I will take a look at the bug once I have more time to do so

**Comment by TimGoll** [comment] 2019-10-08 07:56
The color sync error is sidekick related and happens with other roles too. Therefore I will close this issue now.

**Closed as completed by TimGoll** 2019-10-08 07:56 UTC
